"""Equity research style PDF generation."""

import os
import subprocess
from datetime import datetime
from pathlib import Path

from .base import check_pdf_dependencies
from .emoji_substitution import substitute_emojis


def generate_equity_research_pdf(
    ticker: str,
    company_name: str,
    task_outputs: list,
    section_names: list,
    output_path: str
) -> str:
    """
    Generate a professional equity research style PDF report.
    Features: Rating box, price target, key metrics, dense analysis sections.

    Args:
        ticker: Stock ticker symbol
        company_name: Full company name
        task_outputs: List of CrewAI task output objects
        section_names: List of section names corresponding to task outputs
        output_path: Path for the output PDF

    Returns:
        Path to the generated PDF

    Raises:
        RuntimeError: If pandoc or xelatex are not found
        subprocess.CalledProcessError: If pandoc fails
    """
    check_pdf_dependencies()

    # Create temporary markdown with equity research styling
    temp_md = output_path.replace('.pdf', '_equity_temp.md')
    report_date = datetime.utcnow().strftime("%B %d, %Y")

    with open(temp_md, "w", encoding="utf-8") as f:
        # Header with enhanced styling for professional equity research look
        f.write(f"""---
title: "{company_name}"
subtitle: "Equity Research Report"
author: "AI Investment Research"
date: "{report_date}"
geometry: margin=0.75in
fontsize: 10pt
header-includes:
  - \\usepackage{{fancyhdr}}
  - \\usepackage{{xcolor}}
  - \\usepackage{{colortbl}}
  - \\usepackage{{booktabs}}
  - \\usepackage{{graphicx}}
  - \\usepackage{{array}}
  - \\usepackage{{tabularx}}
  - \\usepackage{{float}}
  - \\usepackage{{titlesec}}
  - \\usepackage{{parskip}}
  - \\usepackage{{amssymb}}
  - \\definecolor{{headerblue}}{{RGB}}{{0,51,102}}
  - \\definecolor{{lightgray}}{{RGB}}{{245,245,245}}
  - \\definecolor{{ForestGreen}}{{RGB}}{{34,139,34}}
  - \\definecolor{{Orange}}{{RGB}}{{255,165,0}}
  - \\definecolor{{Red}}{{RGB}}{{220,20,60}}
  - \\rowcolors{{2}}{{lightgray!15}}{{white}}
  - \\titlespacing*{{\\section}}{{0pt}}{{2.5ex plus 1ex minus .2ex}}{{1.5ex plus .2ex}}
  - \\titlespacing*{{\\subsection}}{{0pt}}{{1.5ex plus 1ex minus .2ex}}{{1ex plus .2ex}}
  - \\titlespacing*{{\\subsubsection}}{{0pt}}{{1ex plus 0.5ex minus .2ex}}{{0.5ex plus .2ex}}
  - \\setlength{{\\parskip}}{{0.6em}}
  - \\pagestyle{{fancy}}
  - \\fancyhead[L]{{\\textbf{{{ticker}}} | {company_name}}}
  - \\fancyhead[R]{{Equity Research}}
  - \\fancyfoot[C]{{\\thepage}}
  - \\fancyfoot[R]{{AI Investment Research}}
---

\\begin{{center}}
\\Large\\textbf{{{ticker}}} | \\textbf{{{company_name}}}
\\end{{center}}

\\vspace{{0.5cm}}

""")

        # Write each section
        for i, task_output in enumerate(task_outputs):
            raw_name = section_names[i] if i < len(section_names) else f"Section {i+1}"
            # Clean section name of emojis
            name = substitute_emojis(raw_name).strip()
            content = task_output.raw.strip()

            # Replace --- separators with *** to avoid YAML parsing issues in pandoc
            lines = content.split('\n')
            processed_lines = []
            for line in lines:
                if line.strip() == '---':
                    processed_lines.append('***')
                else:
                    processed_lines.append(line)
            content = '\n'.join(processed_lines)

            # Substitute emojis with LaTeX-compatible symbols
            content = substitute_emojis(content)

            # Normalize chart paths for pandoc resource resolution
            # Keep full path since reports/charts is in resource-path
            content = content.replace('./reports/charts/', 'reports/charts/')

            f.write(f"# {name}\n\n")
            f.write(content + "\n\n")
            f.write("\\newpage\n\n")

        # Disclaimer
        f.write("""
\\vspace{0.5cm}

## Disclaimer

*This report was generated by an AI-powered investment research system. The information contained herein is for informational purposes only and should not be construed as investment advice. Past performance is not indicative of future results. Investors should conduct their own due diligence before making investment decisions.*

*Data sources: Financial Modeling Prep API, company filings, and public news sources.*
""")

    # Determine resource path for images (charts directory)
    # Use the parent of the output directory as the resource path base
    output_dir = Path(output_path).parent
    resource_paths = [
        str(output_dir),  # Same directory as output
        str(output_dir / "charts"),  # charts subdirectory
        "reports/charts",  # Default charts location
        ".",  # Current directory
    ]
    resource_path = ":".join(resource_paths)

    # Generate PDF
    cmd = [
        "pandoc", temp_md,
        "-o", output_path,
        "--pdf-engine=xelatex",
        "--toc",
        "--toc-depth=2",
        "-V", "documentclass=article",
        "-V", "colorlinks=true",
        "-V", "linkcolor=headerblue",
        "-V", "urlcolor=headerblue",
        f"--resource-path={resource_path}",
    ]
    subprocess.run(cmd, check=True)

    # Clean up temp file
    if os.path.exists(temp_md):
        os.remove(temp_md)

    return output_path
