"""Equity research style PDF generation."""

import os
import subprocess
from datetime import datetime

from .base import check_pdf_dependencies


def generate_equity_research_pdf(
    ticker: str,
    company_name: str,
    task_outputs: list,
    section_names: list,
    output_path: str
) -> str:
    """
    Generate a professional equity research style PDF report.
    Features: Rating box, price target, key metrics, dense analysis sections.

    Args:
        ticker: Stock ticker symbol
        company_name: Full company name
        task_outputs: List of CrewAI task output objects
        section_names: List of section names corresponding to task outputs
        output_path: Path for the output PDF

    Returns:
        Path to the generated PDF

    Raises:
        RuntimeError: If pandoc or xelatex are not found
        subprocess.CalledProcessError: If pandoc fails
    """
    check_pdf_dependencies()

    # Create temporary markdown with equity research styling
    temp_md = output_path.replace('.pdf', '_equity_temp.md')
    report_date = datetime.utcnow().strftime("%B %d, %Y")

    with open(temp_md, "w", encoding="utf-8") as f:
        # Header with rating box style
        f.write(f"""---
title: "{company_name}"
subtitle: "Equity Research Report"
author: "AI Investment Research"
date: "{report_date}"
geometry: margin=0.75in
fontsize: 10pt
header-includes:
  - \\usepackage{{fancyhdr}}
  - \\usepackage{{xcolor}}
  - \\usepackage{{colortbl}}
  - \\usepackage{{booktabs}}
  - \\definecolor{{headerblue}}{{RGB}}{{0,51,102}}
  - \\definecolor{{lightgray}}{{RGB}}{{245,245,245}}
  - \\pagestyle{{fancy}}
  - \\fancyhead[L]{{\\textbf{{{ticker}}} | {company_name}}}
  - \\fancyhead[R]{{Equity Research}}
  - \\fancyfoot[C]{{\\thepage}}
  - \\fancyfoot[R]{{AI Investment Research}}
---

\\begin{{center}}
\\Large\\textbf{{{ticker}}} | \\textbf{{{company_name}}}
\\end{{center}}

\\vspace{{0.5cm}}

---

""")

        # Write each section
        for i, task_output in enumerate(task_outputs):
            name = section_names[i] if i < len(section_names) else f"Section {i+1}"
            f.write(f"# {name}\n\n")
            f.write(task_output.raw.strip() + "\n\n")
            f.write("\\newpage\n\n")

        # Disclaimer
        f.write("""
---

## Disclaimer

*This report was generated by an AI-powered investment research system. The information contained herein is for informational purposes only and should not be construed as investment advice. Past performance is not indicative of future results. Investors should conduct their own due diligence before making investment decisions.*

*Data sources: Financial Modeling Prep API, company filings, and public news sources.*
""")

    # Generate PDF
    cmd = [
        "pandoc", temp_md,
        "-o", output_path,
        "--pdf-engine=xelatex",
        "--toc",
        "--toc-depth=2",
        "-V", "documentclass=article",
        "-V", "colorlinks=true",
        "-V", "linkcolor=headerblue",
        "-V", "urlcolor=headerblue",
    ]
    subprocess.run(cmd, check=True)

    # Clean up temp file
    if os.path.exists(temp_md):
        os.remove(temp_md)

    return output_path
