"""Hedge fund investment memo PDF generation."""

import os
import subprocess
from datetime import datetime

from .base import check_pdf_dependencies


def generate_hedge_fund_memo_pdf(
    ticker: str,
    company_name: str,
    task_outputs: list,
    section_names: list,
    output_path: str
) -> str:
    """
    Generate a concise hedge fund investment memo style PDF.
    Features: Executive summary, thesis-driven, bull/bear cases prominent.

    Args:
        ticker: Stock ticker symbol
        company_name: Full company name
        task_outputs: List of CrewAI task output objects
        section_names: List of section names corresponding to task outputs
        output_path: Path for the output PDF

    Returns:
        Path to the generated PDF

    Raises:
        RuntimeError: If pandoc or xelatex are not found
        subprocess.CalledProcessError: If pandoc fails
    """
    check_pdf_dependencies()

    temp_md = output_path.replace('.pdf', '_memo_temp.md')
    report_date = datetime.utcnow().strftime("%B %d, %Y")

    # Extract key sections for reorganization
    sections_dict = {}
    for i, task_output in enumerate(task_outputs):
        name = section_names[i] if i < len(section_names) else f"Section {i+1}"
        sections_dict[name] = task_output.raw.strip()

    with open(temp_md, "w", encoding="utf-8") as f:
        f.write(f"""---
title: "Investment Memo"
subtitle: "{ticker} | {company_name}"
date: "{report_date}"
geometry: margin=1in
fontsize: 11pt
header-includes:
  - \\usepackage{{fancyhdr}}
  - \\usepackage{{xcolor}}
  - \\definecolor{{darkgreen}}{{RGB}}{{0,100,0}}
  - \\definecolor{{darkred}}{{RGB}}{{139,0,0}}
  - \\pagestyle{{fancy}}
  - \\fancyhead[L]{{\\textbf{{INVESTMENT MEMO}}}}
  - \\fancyhead[R]{{{ticker}}}
  - \\fancyfoot[C]{{\\thepage}}
  - \\fancyfoot[L]{{CONFIDENTIAL}}
---

\\begin{{center}}
\\LARGE\\textbf{{INVESTMENT MEMO}}

\\vspace{{0.3cm}}

\\Large\\textbf{{{ticker}}} | {company_name}

\\vspace{{0.2cm}}

\\normalsize {report_date}
\\end{{center}}

\\vspace{{0.5cm}}

---

""")

        # Executive Summary / Business Profile first
        if "BUSINESS PROFILE" in sections_dict:
            f.write("# Executive Summary\n\n")
            f.write(sections_dict["BUSINESS PROFILE"] + "\n\n")
            f.write("\\newpage\n\n")

        # Business Phase (Investment Stage)
        if "BUSINESS PHASE" in sections_dict:
            f.write("# Investment Stage Analysis\n\n")
            f.write(sections_dict["BUSINESS PHASE"] + "\n\n")
            f.write("\\newpage\n\n")

        # Price & Sentiment (includes Bull/Bear cases)
        if "PRICE & SENTIMENT" in sections_dict:
            f.write("# Market Sentiment & Catalysts\n\n")
            f.write(sections_dict["PRICE & SENTIMENT"] + "\n\n")
            f.write("\\newpage\n\n")

        # Moat Analysis
        if "BUSINESS & MOAT" in sections_dict:
            f.write("# Competitive Position & Moat\n\n")
            f.write(sections_dict["BUSINESS & MOAT"] + "\n\n")
            f.write("\\newpage\n\n")

        # Management & Risk
        if "MANAGEMENT & RISK" in sections_dict:
            f.write("# Key Risks\n\n")
            f.write(sections_dict["MANAGEMENT & RISK"] + "\n\n")
            f.write("\\newpage\n\n")

        # Valuation
        if "QUANT & VALUATION" in sections_dict:
            f.write("# Valuation & Financials\n\n")
            f.write(sections_dict["QUANT & VALUATION"] + "\n\n")

        # Disclaimer
        f.write("""

\\vspace{0.5cm}

\\begin{center}
\\small\\textit{This memo was generated by an AI investment research system for informational purposes only. Not investment advice.}
\\end{center}
""")

    # Generate PDF
    cmd = [
        "pandoc", temp_md,
        "-o", output_path,
        "--pdf-engine=xelatex",
        "-V", "documentclass=article",
        "-V", "colorlinks=true",
    ]
    subprocess.run(cmd, check=True)

    # Clean up temp file
    if os.path.exists(temp_md):
        os.remove(temp_md)

    return output_path
