"""Unified Professional Investment Research Report Generator."""

import os
import re
import subprocess
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Any


class UnifiedReportGenerator:
    """Generates a single comprehensive investment research report."""

    def __init__(self):
        """Initialize report generator."""
        self.reports_dir = Path("reports")
        self.charts_dir = self.reports_dir / "charts"

        # Ensure directories exist
        self.reports_dir.mkdir(exist_ok=True)
        self.charts_dir.mkdir(exist_ok=True)

    def generate_report(
        self,
        ticker: str,
        company_name: str,
        blue_output: Any,
        red_output: Any,
        cio_synthesis: str,
        output_path: str = None
    ) -> str:
        """
        Generate unified professional investment research report.

        Args:
            ticker: Stock ticker symbol
            company_name: Company name
            blue_output: Blue team crew output
            red_output: Red team crew output
            cio_synthesis: CIO synthesis text
            output_path: Optional custom output path

        Returns:
            Path to generated PDF
        """
        if output_path is None:
            output_path = self.reports_dir / f"{ticker}_Investment_Research_Report.pdf"

        # Generate markdown content
        markdown_content = self._generate_markdown(
            ticker,
            company_name,
            blue_output,
            red_output,
            cio_synthesis
        )

        # Save markdown
        md_path = self.reports_dir / f"{ticker}_report.md"
        with open(md_path, "w", encoding="utf-8") as f:
            f.write(markdown_content)

        # Convert to PDF
        self._markdown_to_pdf(md_path, output_path)

        return str(output_path)

    def _generate_markdown(
        self,
        ticker: str,
        company_name: str,
        blue_output: Any,
        red_output: Any,
        cio_synthesis: str
    ) -> str:
        """Generate markdown content for the report."""

        # Extract sections from outputs
        blue_sections = self._extract_sections(blue_output)
        red_sections = self._extract_sections(red_output)

        # Build markdown
        md = []

        # Title page
        md.append(f"""---
title: "Investment Research Report: {company_name} ({ticker})"
subtitle: "Comprehensive Analysis with Red/Blue Team Perspectives"
author: "AI Investment Research System"
date: "{datetime.now().strftime('%B %d, %Y')}"
geometry: margin=1in
fontsize: 11pt
---

\\newpage

""")

        # Table of Contents (will be generated by pandoc)
        md.append("\\tableofcontents\n\n\\newpage\n\n")

        # Section I: Executive Summary (from CIO)
        md.append("# Executive Summary\n\n")
        md.append(cio_synthesis)
        md.append("\n\n\\newpage\n\n")

        # Section II: Investment Debate
        md.append("# Investment Debate: Bull vs Bear\n\n")
        md.append("## The Bull Case (Blue Team Perspective)\n\n")
        md.append(self._format_perspective_summary(blue_sections, "optimistic"))
        md.append("\n\n")

        md.append("## The Bear Case (Red Team Perspective)\n\n")
        md.append(self._format_perspective_summary(red_sections, "skeptical"))
        md.append("\n\n\\newpage\n\n")

        # Section III: Business Overview
        md.append("# Business Overview\n\n")
        md.append(self._merge_section(blue_sections, red_sections, "business_profile"))
        md.append("\n\n")
        md.append(self._merge_section(blue_sections, red_sections, "business_phase"))
        md.append("\n\n\\newpage\n\n")

        # Section IV: Financial Analysis
        md.append("# Financial Analysis\n\n")
        md.append(self._merge_section(blue_sections, red_sections, "key_metrics"))
        md.append("\n\n\\newpage\n\n")

        # Section V: Competitive Positioning
        md.append("# Competitive Positioning & Moat Analysis\n\n")
        md.append(self._merge_section(blue_sections, red_sections, "business_moat"))
        md.append("\n\n\\newpage\n\n")

        # Section VI: Growth Assessment
        md.append("# Growth Assessment\n\n")
        md.append(self._merge_section(blue_sections, red_sections, "growth_drivers"))
        md.append("\n\n\\newpage\n\n")

        # Section VII: Risk Analysis
        md.append("# Risk Analysis\n\n")
        md.append("## Execution Risk\n\n")
        md.append(self._merge_section(blue_sections, red_sections, "execution_risk"))
        md.append("\n\n")
        md.append("## Management Quality\n\n")
        md.append(self._merge_section(blue_sections, red_sections, "management_risk"))
        md.append("\n\n\\newpage\n\n")

        # Section VIII: Valuation
        md.append("# Valuation Analysis\n\n")
        md.append(self._merge_section(blue_sections, red_sections, "visual_valuation"))
        md.append("\n\n")
        md.append(self._merge_section(blue_sections, red_sections, "quant_valuation"))
        md.append("\n\n\\newpage\n\n")

        # Section IX: Market Sentiment
        md.append("# Market Sentiment & Price Action\n\n")
        md.append(self._merge_section(blue_sections, red_sections, "price_sentiment"))
        md.append("\n\n\\newpage\n\n")

        # Section X: Investment Scorecards
        md.append("# Investment Scorecards\n\n")
        md.append("## Blue Team Scorecard\n\n")
        md.append(blue_sections.get("investment_scorecard", ""))
        md.append("\n\n")
        md.append("## Red Team Scorecard\n\n")
        md.append(red_sections.get("investment_scorecard", ""))
        md.append("\n\n\\newpage\n\n")

        # Section XI: Appendix
        md.append("# Appendix\n\n")
        md.append("## Methodology\n\n")
        md.append("""This report was generated using a Red Team / Blue Team analytical framework:

- **Blue Team**: Analyzed the company with an optimistic lens, identifying strengths, opportunities, and reasons to invest
- **Red Team**: Analyzed the company with a skeptical lens, identifying weaknesses, risks, and reasons for caution
- **Chief Investment Officer**: Synthesized both perspectives to make an independent investment recommendation

This approach reduces confirmation bias and ensures rigorous analysis from multiple perspectives.
""")
        md.append("\n\n")

        md.append("## Report Generation\n\n")
        md.append(f"- **Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC')}\n")
        md.append(f"- **Ticker:** {ticker}\n")
        md.append(f"- **Company:** {company_name}\n")
        md.append("- **System:** AI Investment Research with CrewAI\n")

        content = "".join(md)
        # Replace horizontal rules (---) with (***) to prevent pandoc from
        # interpreting them as YAML document markers after the frontmatter.
        # We need to preserve the YAML frontmatter delimiters (first two ---)
        # so we split on them, process the body, then rejoin.
        parts = content.split('---', 2)
        if len(parts) >= 3:
            # parts[0] is empty (before first ---), parts[1] is frontmatter, parts[2] is body
            body = parts[2]
            # Replace --- horizontal rules (with optional trailing whitespace)
            body = re.sub(r'\n---[ \t]*\n', '\n***\n', body)
            content = '---'.join(parts[:2]) + '---' + body
        return content

    def _extract_sections(self, crew_output: Any) -> Dict[str, str]:
        """Extract individual sections from crew output."""
        sections = {}

        if hasattr(crew_output, 'tasks_output'):
            task_mapping = {
                0: "price_sentiment",
                1: "business_phase",
                2: "key_metrics",
                3: "business_profile",
                4: "business_moat",
                5: "execution_risk",
                6: "growth_drivers",
                7: "management_risk",
                8: "visual_valuation",
                9: "quant_valuation",
                10: "investment_scorecard",
            }

            for i, task_output in enumerate(crew_output.tasks_output):
                section_key = task_mapping.get(i, f"section_{i}")
                sections[section_key] = task_output.raw if hasattr(task_output, 'raw') else str(task_output)

        return sections

    def _format_perspective_summary(self, sections: Dict[str, str], perspective: str) -> str:
        """Format a summary of a team's perspective."""
        summary = []

        if "investment_scorecard" in sections:
            summary.append(sections["investment_scorecard"])
        else:
            summary.append(f"*{perspective.capitalize()} perspective analysis*\n\n")
            # Include key sections as summary
            for key in ["business_moat", "growth_drivers", "execution_risk"]:
                if key in sections:
                    summary.append(sections[key][:500] + "...\n\n")

        return "\n".join(summary)

    def _merge_section(
        self,
        blue_sections: Dict[str, str],
        red_sections: Dict[str, str],
        section_key: str
    ) -> str:
        """Merge a section from both teams into a comparative view."""
        blue = blue_sections.get(section_key, "")
        red = red_sections.get(section_key, "")

        if not blue and not red:
            return "*No data available for this section.*"

        # For most sections, show both perspectives side-by-side
        merged = []

        merged.append(f"### Blue Team Perspective (Optimistic)\n\n")
        merged.append(blue if blue else "*No blue team analysis.*")
        merged.append("\n\n")

        merged.append(f"### Red Team Perspective (Skeptical)\n\n")
        merged.append(red if red else "*No red team analysis.*")
        merged.append("\n\n")

        return "".join(merged)

    def _markdown_to_pdf(self, md_path: Path, pdf_path: Path) -> None:
        """Convert markdown to PDF using pandoc."""
        try:
            # Use pandoc with xelatex for better formatting
            cmd = [
                "pandoc",
                str(md_path),
                "-o", str(pdf_path),
                "--pdf-engine=xelatex",
                "--toc",
                "--toc-depth=2",
                "-V", "geometry:margin=1in",
                "-V", "fontsize=11pt",
                "-V", "documentclass=article",
            ]

            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                check=True
            )

            print(f"✅ PDF generated: {pdf_path}")

        except subprocess.CalledProcessError as e:
            print(f"❌ PDF generation failed: {e}")
            print(f"Stdout: {e.stdout}")
            print(f"Stderr: {e.stderr}")
            print(f"✅ Markdown report available at: {md_path}")
        except FileNotFoundError:
            print("❌ pandoc not found. Install with: sudo apt-get install pandoc texlive-xetex")
            print(f"✅ Markdown report available at: {md_path}")
